import 'package:countries/models/country_model.dart';
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

part 'api_client.g.dart'; // This file will be generated by Retrofit

@RestApi(baseUrl: "https://restcountries.com/v3.1")
abstract class ApiClient {
  factory ApiClient(Dio dio, {String baseUrl}) = _ApiClient;

  @GET("/region/europe")
  Future<List<Country>> getCountries(
    @Query("fields") String fields,
  );
}
